baseurl = "https://mfaltys.github.io/redns_docs/"
languageCode = "en-us"
title = "redns-docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true

[params]
	# General information
	author = "Matthew Faltys"
	description = "Redns documentation."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/mfaltys/redns"

	version = "v0.95.0"
	logo = "img/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "indigo"
    	accent  = "teal"

    [params.font]
    	text = "Source Sans Pro"
    	code = "Source Code Pro"


[social]
	twitter = "thefaltyone"
	github  = "mfaltys"
	email   = "mfaltys@gmail.com"


[[menu.main]]
	name   = "Redns"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Quickstart"
	url    = "quickstart/index"
	weight = 10

[[menu.main]]
	name   = "Configuration"
	url    = "configuration/index"
	weight = 10

[[menu.main]]
	name   = "Redns CLI commands"
	url    = "cli/index"
	weight = 10

[[menu.main]]
	name   = "Milestone 1"
	url    = "milestone.1/index"
	weight = 10

[[menu.main]]
	name   = "Milestone 2"
	url    = "milestone.2/index"
	weight = 10

[[menu.main]]
	name   = "Milestone 3"
	url    = "milestone.3/index"
	weight = 10

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
